Fix build process and CI (#32)
* Test againts openjdk8

* Codenarc updated to 1.0

Removes error:
Execution failed for task ':codenarcTest'.
> java.lang.NoClassDefFoundError: groovy/text/SimpleTemplateEngine
https://discuss.gradle.org/t/sudden-issue-with-gradle-3-5-1-and-codenarc/30064/4